on:
  push:
    branches: [ nextjs ]
  pull_request:
    branches: [ nextjs ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install
      
    - name: Build App
      run: yarn build
      
    - uses: Cecilapp/GitHub-Pages-deploy@v3
      


   
