on:
  push:
    branches: [ nextjs ]
  pull_request:
    branches: [ nextjs ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install
      
    - name: Build App
      run: yarn build

    - name: Deploy to GitHub Pages
    - uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        email: username@domain.tld
        build_dir: out               # optional
        branch: gh-pages                # optional
        #cname: domain.tld              # optional
        jekyll: no                     # optional
        #commit_message: custom message # optional
    
